# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68155ad4ddd25784e940e2e23abe196b6090bd5ceada4e8d72908a2f6de55e010ab59aa79289c204b69bef0fb95723551a7b6185711fe1540f20de3664263075

test:
  secret_key_base: 3875976dad7430a4a4f5af947a0c5e602f1e1bbd7fa056e59436f73a1ff5e12dc1b7d51017903a9d161da890fb3c36f1044778c62d25a28d3b502dce806e64e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
